use_frameworks!

platform :ios, '10.0'

target 'JPComponents_Example' do
  pod 'JPComponents', :path => '../'

  target 'JPComponents_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
